sudo: required

language: php

services:
    - docker

php:
    - '7.1'

branches:
    only:
        - feature/init-tests

before_install:
    - docker pull vault

before_script:
    - composer install --no-interaction --dev
    - docker run -p 8200:8200 --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=f29e2a2f-26ac-a182-b7a9-05be2381e200' vault

script:
    - phpunit